# Generated by Django 4.1 on 2022-09-03 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("writing", "0002_comment"),
    ]

    operations = [
        migrations.DeleteModel(name="Comment",),
    ]
